event-planner/API/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView

from API import views 

app_name = 'API'

urlpatterns = [
 
    path('list/', views.EventList.as_view(), name='API_list'), 
    path('org_list/<int:owner_id>/', views.OrgList.as_view(), name='API_org_list'),
    path('booking/list/', views.BookingList.as_view(), name='API_booking_list'),
    path('create/', views.CreateEvent.as_view(), name='API_create'),
    path('update/<int:event_id>/', views.UpdateEvent.as_view(), name='API_update'),
    path('detail/<int:event_id>/', views.EventDetails.as_view(), name='API_detail'),
    path('book/<int:event_id>/', views.BookEvent.as_view(), name='API_book'),

    path('register/', views.Register.as_view(), name="register"),
    path('login/', TokenObtainPairView.as_view(), name='login'),

]

event-planner/event_planner/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls', namespace='events')),
    path('api/', include('API.urls', namespace='api')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event-planner/events/urls.py
from django.urls import path

from events import views

app_name = 'events'

urlpatterns = [

	path('home/', views.home, name='home'),

	path('create/', views.create_event, name='create'),
	path('list/', views.event_list, name='list'),
	path('detail/<int:event_id>/', views.event_detail, name='detail'),
	path('edit/<int:event_id>/', views.event_edit, name='edit'),
	path('booking/<int:event_id>/', views.booking, name='booking'),
	path('cancel/<int:booking_id>/', views.cancel_booking, name='cancel'),

	path('dashboard/', views.dashboard, name='dashboard'),

    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name= 'login'),
    path('logout/', views.Logout.as_view(), name='logout'),

]

event-planner/events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Event(models.Model):
    owner = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name='organizer')
    title = models.CharField(max_length=150)
    description = models.TextField()
    location = models.CharField(max_length=150)
    date = models.DateField()
    time = models.TimeField()
    seats = models.IntegerField()

    def get_seats_booked(self):
        books = self.bookings.all()
        total = 0
        for book in books:
            total = total + book.num_seats
        return total

    def get_seats_left(self):
        return self.seats - self.get_seats_booked()

    def full(self):
        return self.get_seats_left == 0

    def get_absolute_url(self):
        return reverse('events:detail', kwargs={'event_id':self.id})

    def __str__(self):
        return self.title


class Booking(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name='attended')
    num_seats = models.IntegerField()
    event = models.ForeignKey(Event, default=1, on_delete=models.CASCADE, related_name='bookings')

    def __str__(self):
        return self.user.username

event-planner/events/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Event,Booking


class UserSignup(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email' ,'password']

        widgets={
        'password': forms.PasswordInput(),
        }


class UserLogin(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput())


class DateInput(forms.DateInput):
    input_type = 'date'


class TimeInput(forms.TimeInput):
    input_type ='time'



class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude =['owner']

        widgets={
        'date': DateInput(),
        'time': TimeInput(),
            } 




class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields =['num_seats']

event-planner/events/views.py
from django.views import View
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from .models import Event, Booking
from .forms import UserSignup, UserLogin, EventForm ,BookingForm

from datetime import datetime, date
import datetime as dt
from django.db.models import Q
from django.utils import timezone


def home(request):
    return render(request, 'home.html')

class Signup(View):
    form_class = UserSignup
    template_name = 'signup.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            messages.success(request, "You have successfully signed up.")
            login(request, user)
            return redirect("events:home")
        messages.warning(request, form.errors)
        return redirect("events:signup")

class Login(View):
    form_class = UserLogin
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            auth_user = authenticate(username=username, password=password)
            if auth_user is not None:
                login(request, auth_user)
                messages.success(request, "Welcome Back!")
                return redirect('events:dashboard')
            messages.warning(request, "Wrong email/password combination. Please try again.")
            return redirect("events:login")
        messages.warning(request, form.errors)
        return redirect("events:login")


class Logout(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, "You have successfully logged out.")
        return redirect("events:login")



def create_event(request):
    if request.user.is_anonymous:
        messages.warning(request, "You have to log in first!")
        return redirect("events:home")
    form = EventForm()
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event=form.save(commit=False)
            event.owner = request.user
            event.save()
            messages.success(request, "Successfully Created!")
            return redirect('events:list')
        print (form.errors)
    context = {
    "form": form,
    }
    return render(request, 'create.html', context)


def event_list(request):
    if request.user.is_anonymous:
        messages.warning(request, "You have to log in first!")
        return redirect("events:home")
    events = Event.objects.filter(date__gte=datetime.today())
    query = request.GET.get('q')
    if query:
        events = events.filter(
            Q(title__icontains = query)|
            Q(owner__username__icontains = query)|
            Q(description__icontains =query)).distinct()
    context = {
        "events": events,
    }
    return render(request, 'list.html', context)


def event_detail(request,event_id):
    if request.user.is_anonymous:
        messages.warning(request, "You have to log in first!")
        return redirect("events:home")
    event = Event.objects.get(id=event_id)
    context = {
        "event": event,
    }
    return render(request, 'detail.html', context)


def event_edit(request,event_id):
    if request.user.is_anonymous:
        messages.warning(request, "You have to log in first!")
        return redirect("events:home")
    event=Event.objects.get(id=event_id)
    owner = event.owner
    if not owner == request.user:
         messages.warning(request, "You are not authorized to edit this event!")
         return redirect("events:list")
    form = EventForm(instance = event)
    if request.method == "POST":
        form = EventForm(request.POST , instance=event)
        if form.is_valid():
            form.save()
            return redirect('events:list')
    context = {
        "event": event,
        "form": form,
    }
    return render(request, 'edit.html', context)


def dashboard(request):
    if request.user.is_anonymous:
        messages.warning(request, "You have to log in first!")
        return redirect("events:home")
    past_events = Booking.objects.filter(user = request.user, event__date__lt=datetime.today()).order_by("event__date", "event__time")
    upcoming_events = Booking.objects.filter(user = request.user, event__date__gte=datetime.today()).order_by("event__date", "event__time")
    context = {
        "past_events": past_events,
        "upcoming_events": upcoming_events,
    }
    return render (request, "dashboard.html", context)


def booking(request, event_id):
    if request.user.is_anonymous:
        messages.warning(request, "You have to log in first!")
        return redirect("events:home")
    form = BookingForm()
    event = Event.objects.get(id=event_id)
    if request.method == "POST":
        form = BookingForm(request.POST)
        if form.is_valid():
            book=form.save(commit=False)
            book.user = request.user
            book.event = event
            seats = int(book.num_seats)
            if seats > event.get_seats_left():
                messages.warning(request, "You are exceeding the seats limit! There are only {} seats left".format(event.get_seats_left()))
            else:
                book.save()
                messages.success(request, "Successfully booked!")
                return redirect('events:dashboard')
        print (form.errors)
    context = {
        "form": form,
        "event": event,
    }
    return render(request, 'booking.html', context)

def cancel_booking(request, booking_id):
    if request.user.is_anonymous:
        messages.warning(request, "You have to log in first!")
        return redirect("events:home")
    booking=Booking.objects.get(id=booking_id)
    owner = booking.user
    if not owner == request.user:
         messages.warning(request, "You are not authorized to cancel this booking!")
         return redirect("events:dashboard")
    hours_left = datetime.combine(date.today(), booking.event.time) - datetime.combine(date.today(), timezone.now().time())
    if hours_left < dt.timedelta(hours=3):
        messages.warning(request, "Booking can not be cancled unless more than 3 hours are left!")
        return redirect("events:dashboard")
    booking.delete()
    messages.success(request, "Successfully Deleted!")
    return redirect('events:dashboard')

event-planner/events/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Django Event Planner</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">
    <style>
        html {
          position: relative;
          min-height: 100%;
        }
        body {
          margin-bottom: 60px;

        }
        .jumbotron{
            background-color: black;
        }
        .messages{
            position: absolute;
            margin-top: 67px;
            z-index: 10;
            width: 100%;
        }
        #test{
            background-color: transparent;
            border-color: #FFD23F;
            border-width: 5px;
            color:white;
          
        }
        

    </style>
  </head>

  <body>
    {% include "navbar.html" %}
    {% include "messages.html" %}
    
    {% block content %}

    {% endblock %}


    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

event-planner/events/templates/booking.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class = "container create_form">
	<form action="{% url 'events:booking' event.id%}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="book" class="btn" style="background-color: #e3f2fd; color: black;">
	</form>
</div>
{% endblock content %}

event-planner/events/templates/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class = "container create_form">
	<form action="{% url 'events:create' %}" method="POST">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="Create" class="btn create">
	</form>
</div>
{% endblock content %}

event-planner/events/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
<a class="nav-link create_btn" href="{% url 'events:create' %}">Create Event</a>
  <div class = 'container'>
  <p class = "table_title" style = "margin-top: 50px;"> Events by me </p>
  <table class="table table-bordered table-dark" style="margin-bottom: 50px;">
    <thead>
      <tr>
         <th scope="col">Title </th>
        <th scope="col">Location </th>
        <th scope="col">Date </th>
        <th scope="col">time </th>
      </tr>
    </thead>
    <tbody>
      {% for event in request.user.organizer.all %}
        <tr>
          <td> {{event.title}} </td>
          <td> {{event.location}}</td>
          <td> {{event.date}} </td>
           <td> {{event.time}} </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>

  <div class = 'container'>
    <p class = "table_title"> Attended by me </p>
    <table class="table table-bordered table-dark">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Location</th>
          <th scope="col">Date </th>
          <th scope="col">time </th>
        </tr>
      </thead>
      <tbody>
        {% for e in past_events %}
          <tr> 
            <td> {{e.event.title}} </td>
            <td> {{e.event.location}}</td>
            <td> {{e.event.date}} </td>
            <td> {{e.event.time}} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class = 'container'>
    <p class = "table_title"> To be attended </p>
    <table class="table table-bordered table-dark">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Location</th>
          <th scope="col">Date </th>
          <th scope="col">Time </th>
          <th scope="col">Cancel </th>
        </tr>
      </thead>
      <tbody>
        {% for e in upcoming_events %}
          <tr> 
            <td> {{e.event.title}} </td>
            <td> {{e.event.location}}</td>
            <td> {{e.event.date}} </td>
            <td> {{e.event.time}} </td>
            <td> <a class="nav-link create_btn" href="{% url 'events:cancel' e.id %}">Cancel booking</a> </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}

event-planner/events/templates/detail.html
{% extends "base.html" %}

{% block title %}Detail{% endblock title %}

{% block content %}

<br>
<div class="card">
  <h5 class="card-header">Event Info</h5>
  <div class="card-body">
    <h5 class="card-title">Title: {{event.title}}</h5>
    <p class="card-text"> Description: {{event.description}}</p>
    <p class="card-text"> Location: {{event.location}}</p>
    <p class="card-text"> Date: {{event.date}}</p>
    <p class="card-text"> Time: {{event.time}}</p>
    <p class="card-text"> Seats: {{event.seats}}</p>
    <p class="card-text"> Seats Left: {{event.get_seats_left}}</p>
    {% if request.user == event.owner %}
        <a href="{% url 'events:edit' event.id %}" class="btn" style="background-color: #FFA500; color: #000034;"> edit </a>
    {%endif %}
  </div>
</div>
 {% if request.user == event.owner %}
<table class="table">
  <thead>

    <tr>
       <th scope="col">Username</th>
      <th scope="col">Seats</th>
    </tr>
  </thead>
  <tbody>
    {% for u in event.bookings.all %}
      <tr>
        <td> {{u.user.username}} </td>
        <td> {{u.num_seats}} </td>
      </tr>
    {% endfor %}
  
  </tbody>
</table>
{%endif %}
{% endblock content %}

event-planner/events/templates/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<form action="{% url 'events:edit' event.id %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="edit" class="btn" style="background-color: #e3f2fd; color: white;">
	</form>
{% endblock content %}

event-planner/events/templates/home.html
{% extends "base.html" %}

{% block content %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">All the events,</h1>
      <h2 class="masthead-subheading mb-0">You could ever want...</h2>
      {% if request.user.is_anonymous %}
        <a href="{% url 'events:signup' %}" class="btn btn-primary btn-xl rounded-pill mt-5">Sign up to find events!</a>
      {% else %}
        <a href="{% url 'events:list' %}" id = "test" class="btn btn btn-xl rounded-pill mt-5">Find events!</a>
      {% endif %}
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

event-planner/events/templates/list.html
{% extends "base.html" %}

{% block title %}List{% endblock title %}

{% block content %}
<br>
<form action="{% url 'events:list' %}" method="GET">
    <input type="text" name='q' placeholder="Search here..." value="{{request.GET.q}}" 
    style= "margin: 10px">
    <input type="submit" value="Search">
</form>

<div class="row">
    {% for event in events %}
    <div class="col-md-4">
        <div class="card my-card" style= "margin: 10px">
          <div class="card-body">
            <h5 class="card-title"> Name :{{event.title}}</h5>
            <a href="{{event.get_absolute_url}}" class="btn btn-outline-dark">View more</a> 
            {% if event.full %}
              <button class="btn btn-danger">FULL</button>
            {% else %}
              <a href="{% url 'events:booking' event.id %}" class="btn btn-outline-dark">Book</a>
            {% endif %}
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

event-planner/events/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
        <div class="jumbotron">
          <h2 class="masthead-subheading mb-0">Log In</h2>
          <form action="{% url 'events:login' %}" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input class = "btn btn-primary btn-xl rounded-pill mt-5" type="submit" value="Login">
          </form>
      </div>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

event-planner/events/templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
    	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    		<span aria-hidden="true">&times;</span>
    	</button>
    	{{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

event-planner/events/templates/navbar.html
<nav class="navbar navbar-expand-lg  navbar-custom ">
  <div class="container">
    <a class="navbar-brand" style = "color: black" href="{% url 'events:home' %}">Django Event Planner</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_anonymous %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events:signup' %}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events:login' %}">Log In</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events:logout' %}">Log Out</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events:dashboard' %}">{{ request.user }}</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

event-planner/events/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
        <div class="jumbotron">
          <h2 class="masthead-subheading mb-0">Sign Up</h2>
          <form action="{% url 'events:signup' %}" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input class = "btn btn-primary btn-xl rounded-pill mt-5" type="submit" value="Sign Up">
          </form>
      </div>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}